import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col justify-between gap-[2px] bg-gray-500 [&>*]:bg-black">
        <div className="flex shrink-0 grow-0 justify-between">
          <div>Prof Pic</div>
          <div>Dynamic Icons</div>
        </div>
        <div className="grow">{children}</div>
        <div className="flex shrink-0 grow-0 justify-between">
          <div>Home</div>
          <div>Search</div>
          <div>Communities</div>
          <div>Notifications</div>
          <div>Messages</div>
        </div>
      </body>
    </html>
  );
}
