import "./globals.css";

import DynamicHeader from "@/components/DynamicHeader";
import NavBar from "@/components/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col justify-between [&>*]:bg-black">
        <div className="flex h-[52px] shrink-0 grow-0 justify-between">
          <DynamicHeader />
        </div>
        <div className="grow overflow-y-scroll">{children}</div>
        <div className="flex shrink-0 grow-0 justify-around border-t">
          <NavBar />
        </div>
      </body>
    </html>
  );
}
