import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between gap-[2px]">
        <div className="flex justify-between">
          <div>Prof Pic</div>
          <div>Settings</div>
        </div>
        <div>{children}</div>
        <div className="flex justify-between">
          <div>Home</div>
          <div>Search</div>
          <div>Communities</div>
          <div>Notifications</div>
          <div>Messages</div>
        </div>
      </body>
    </html>
  );
}
